#!/usr/bin/expect -f
      set host [lindex $argv 0]
      set port [lindex $argv 1]
      set user [lindex $argv 2]
      set password [lindex $argv 3]
      set key [lindex $argv 4]
      set timeout -1

      spawn ssh -i $key $user@$host -p $port
      expect "*passphrase*"
      send "$password"
      interact
      expect eof
