#!/usr/bin/expect -f
      set host  [lindex $argv 0]
      set port  [lindex $argv 1]
      set user  [lindex $argv 2]
      set password  [lindex $argv 3]
      set timeout -1

      spawn ssh $user@$host -p $port
      expect "*assword:*"
      send "$password"
      interact
      expect eof
